### PR TITLE
added drift boss

### PR DESCRIPTION
**Pull request by SipSup3314**
3kh0/3kh0.github.io#31
3kh0/3kh0.github.io#61

### CODE REVIEW

**Comment by 3kh0** [comment]
alr i will make sure it works

**Comment by SipSup3314** [comment]
noice

**Review by Nebelung-Dev — APPROVED** [review]
Seems good

**Comment by Russell2259** [comment]
Source url for mathplayground: https://www.mathplayground.com/drift-boss-v3/index.html

**Pull request merged**
