### PR TITLE
add games

### PR DESCRIPTION
**Pull request by Rahib777-7**

### CODE REVIEW

**Comment by Rahib777-7** [comment]
im glad 3kh0's site is back!

**Review by 3kh0 — CHANGES_REQUESTED** [review]
remove the `lets-surf-ms-edge` folder

**Comment by Russell2259** [comment]
@Rahib777-7 Please update your branch.

**Comment by Rahib777-7** [comment]
> remove the `lets-surf-ms-edge` folder

done 
> @Rahib777-7 Please update your branch.
done

**Review by LiamM-MTCBs — APPROVED** [review]

**Pull request merged**
