### PR TITLE
Add Drift Boss

### PR DESCRIPTION
**Pull request by Russell2259**
Added working version of drift boss.

Demo: [https://raw.githack.com/Russell2259/3kh0-Assets/main/drift-boss/index.html](https://raw.githack.com/Russell2259/3kh0-Assets/main/drift-boss/index.html)

3kh0/3kh0.github.io#31

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
image

it just gets stuck on loading

**Comment by Russell2259** [comment]
@3kh0 Ahhh, It might be because I'm trying to make a game ripper. Files probably got corrupted.

**Comment by Russell2259** [comment]
@3kh0 Fixed

**Comment by Russell2259** [comment]
@3kh0 Idk why its broken it works just fine on my test.

**Pull request closed without merging**
