### PR TITLE
add  super auto pets

### PR DESCRIPTION
**Pull request by Rahib777-7**

### CODE REVIEW

**Comment by Russell2259** [comment]
@Rahib777-7 Can't play the game. [https://raw.githack.com/Rahib777-7/3kh0-assets/main/yohoho/index.html](https://raw.githack.com/Rahib777-7/3kh0-assets/main/yohoho/index.html)

**Comment by Rahib777-7** [comment]
> @Rahib777-7 Can't play the game. https://raw.githack.com/Rahib777-7/3kh0-assets/main/yohoho/index.html

almost forgot to test it and it doesnt work so im replacing it with different game

**Comment by Rahib777-7** [comment]
replaced @Russell2259

**Comment by Russell2259** [comment]
@Rahib777-7 Why did you add the scratch version? There is a url for a reason.

[https://teamwood.itch.io/super-auto-pets](https://teamwood.itch.io/super-auto-pets)

**Comment by Rahib777-7** [comment]
> @Rahib777-7 Why did you add the scratch version? There is a url for a reason.
> 
> https://teamwood.itch.io/super-auto-pets

simpler to add and its same thing

**Pull request closed without merging**
