### PR TITLE
Fixed Learn to fly 2

### PR DESCRIPTION
**Pull request by amhooman**
yes

### CODE REVIEW

**Comment by Russell2259** [comment]
@amhooman It looks like you missed some files: [https://raw.githack.com/amhooman/3kh0-Assets/main/learntofly2/index.html](https://raw.githack.com/amhooman/3kh0-Assets/main/learntofly2/index.html)

**Comment by 3kh0** [comment]
image

**Comment by amhooman** [comment]
idk what I did. I broke it somehow. gotta look into it

**Comment by Russell2259** [comment]
I'm going to close this for now, if it can be fixed create a new pull request.

**Pull request closed without merging**
