### PR TITLE
Add Games

### PR DESCRIPTION
**Pull request by host008**
added dogeminer 2(https://dogeminer2.com/)
and level13(https://nroutasuo.github.io/level13/)

### CODE REVIEW

**Comment by host008** [comment]
added final earth 2(saw you had 1 but not 2)

**Comment by 0vns** [comment]
hi anyone there

**Comment by Russell2259** [comment]
@host008 Please update your branch

**Comment by tgcofficial** [comment]
added monster tracks, cool

**Comment by host008** [comment]
@tgcofficial added monster tracks via pull request

**Review by host008 — COMMENTED** [review]
gud

**Review by Russell2259 — CHANGES_REQUESTED** [review]
Open a pr in [3kh0.github.io](https://github.com/3kh0/3kh0.github.io) with an updated games file.

**Comment by host008** [comment]
3kh0/3kh0.github.io#133

**Comment by Russell2259** [comment]
@host008 Please update your fork.

**Comment by tgcofficial** [comment]
thanks, what else do u need me to do.

**Comment by host008** [comment]
fork updated

**Comment by Russell2259** [comment]
@host008 It's not updated

**Comment by host008** [comment]
wdym

**Comment by Russell2259** [comment]
@host008 Click on the button that says sync fork on your fork of 3kh0-assets.

**Comment by host008** [comment]
synced

**Review by Russell2259 — APPROVED** [review]
looks good

**Pull request merged**
