### PR TITLE
delete dr doe chem quiz because innapropriate

### PR DESCRIPTION
**Pull request by DapperLS-Bot-Dev**

### CODE REVIEW

**Comment by Rahib777-7** [comment]
but its just a questioning game?

**Comment by DapperLS-Bot-Dev** [comment]
Get 10/10 and it shows sex scene

**Comment by Rahib777-7** [comment]
> Get 10/10 and it shows sex scene

i moved it to the bottom

**Comment by Rahib777-7** [comment]
nobody's gonna play it now

**Comment by DapperLS-Bot-Dev** [comment]
So what?

**Comment by Rahib777-7** [comment]
> So what?

its kool gaem

**Comment by Rahib777-7** [comment]
> Get 10/10 and it shows sex scene

actually lets get rid of it

**Comment by Rahib777-7** [comment]
3kh0 isnt rated for kids safe sooo its fine

**Pull request merged**
